# Simple Computer Vision for Fashion MNIST

## Purpose
This notebook provides you a simple computer vision analysis for Fashion MNIST Dataset with the explanation for the steps that has been taken. I hope that this will help everyone who wants to start learning computer vision using TensorFlow (including me üòÅ)

## Data Analysis

### Import Library Needed

In this analysis, we are going to use two libraries, namely:
1. Pandas for data processing (https://pandas.pydata.org/)
2. TensorFlow for machine learning (https://www.tensorflow.org/)

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import tensorflow as tf # machine learning

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/fashionmnist/t10k-labels-idx1-ubyte
/kaggle/input/fashionmnist/t10k-images-idx3-ubyte
/kaggle/input/fashionmnist/fashion-mnist_test.csv
/kaggle/input/fashionmnist/fashion-mnist_train.csv
/kaggle/input/fashionmnist/train-labels-idx1-ubyte
/kaggle/input/fashionmnist/train-images-idx3-ubyte

### Read Training and Testing Data

In this step, we will read the training data that have been provided. The data are already separated into training data and testing data. So, we don't have to split the data.

In [2]:
'''
Read Training Data
'''
df_train = pd.read_csv('../input/fashionmnist/fashion-mnist_train.csv')
df_train.head(3)

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6,0,0,0,0,0,0,0,5,0,...,0,0,0,30,43,0,0,0,0,0

In [3]:
'''
Read Testing Data
'''
df_test = pd.read_csv('../input/fashionmnist/fashion-mnist_test.csv')
df_test.head(3)

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,0,9,8,...,103,87,56,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,34,0,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,14,53,99,...,0,0,0,0,63,53,31,0,0,0

### Extract Features from the Training and Testing Data

The training and testing data contains both the features and the label. In this dataset, the features itself is the pixel of the images. The data training features itself will be normalized (by dividing the pixel with 255 since the pixel of the image is ranging from 1 to 255).

In [4]:
'''
Extract features from the training data
'''
df_train_features = df_train.iloc[:, 1:]
df_train_features = df_train_features / 255.0
df_train_features

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.019608,0.0,0.0,...,0.000000,0.000000,0.000000,0.117647,0.168627,0.000000,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.003922,0.007843,0.0,0.0,0.000000,0.0,0.0,...,0.011765,0.000000,0.000000,0.000000,0.000000,0.003922,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
59996,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,...,0.286275,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
59997,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,...,0.627451,0.635294,0.639216,0.529412,0.368627,0.000000,0.0,0.0,0.0,0.0
59998,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
59999,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0

In [5]:
'''
Extract features from the testing data
'''
df_test_features = df_test.iloc[:, 1:]
df_test_features

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,9,8,0,...,103,87,56,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,34,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,14,53,99,17,...,0,0,0,0,63,53,31,0,0,0
3,0,0,0,0,0,0,0,0,0,161,...,137,126,140,0,133,224,222,56,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,0,0,0,0,0,0,0,0,37,...,32,23,14,20,0,0,1,0,0,0
9996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,52,23,28,0,0,0
9997,0,0,0,0,0,0,0,0,0,0,...,175,172,172,182,199,222,42,0,1,0
9998,0,1,3,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
9999,0,0,0,0,0,0,0,140,119,103,...,111,95,75,44,1,0,0,0,0,0

### Extract Labels from the Training and Testing Data

The labels are the category of every image, which are:
* (0) T-shirt/top
* (1) Trouser
* (2) Pullover
* (3) Dress
* (4) Coat
* (5) Sandal
* (6) Shirt
* (7) Sneaker
* (8) Bag
* (9) Ankle boot

In [6]:
'''
Extract labels from the training data
'''
df_train_label = df_train.iloc[:, 0]
df_train_label

0        2
1        9
2        6
3        0
4        3
        ..
59995    9
59996    1
59997    8
59998    8
59999    7
Name: label, Length: 60000, dtype: int64

In [7]:
'''
Extract labels from the testing data
'''
df_test_label = df_test.iloc[:, 0]
df_test_label

0       0
1       1
2       2
3       2
4       3
       ..
9995    0
9996    6
9997    8
9998    8
9999    1
Name: label, Length: 10000, dtype: int64

### Create, Train, and Evaluate Model

After the training and testing data is ready, we are going to use Sequential which is a group of neural network layers [1]. We will only use Dense Layer which is just a regular neural network layer with 64 and 10 as unit (dimensionality of the output space) [2]. The input shape is the shape of the data which is 784 (784 pixel). In the other condition, you have to use Flatten Layer to flatten your input [3] (for example: 28px * 28px image needs to be flatten first in the first layer of the Sequential).

There are some other important notes for the model, which is:
* ReLU activation is an activation which will output the input directly if it is positive and return zero if it is not positive [4]
* Softmax activation is an activation which return the probability of each class [5] which in this case is the 10 label of the class (that's why we are using 10 as units of the Dense Layer)
* Adam optimizer is a stochastic gradient descent method that will provides some benefits, for example efficient computational [6]
* Sparse Categorical Crossentropy is a loss function that will be used for more than two label classes (we have 10 label) and for the label that is not One Hot Encoded [7]
* We include accuracy metric that will be calculated when we train the model

In [8]:
'''
Create model
'''

model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(256, activation='relu', input_shape=(784,)), 
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [9]:
'''
Train model
'''

model.fit(df_train_features, df_train_label, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.6106 - accuracy: 0.7848
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3772 - accuracy: 0.8632
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3350 - accuracy: 0.8778
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3066 - accuracy: 0.8873
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2871 - accuracy: 0.8941

In [10]:
'''
Evaluate Model
'''

model.evaluate(df_test_features, df_test_label)

313/313 [==============================] - 1s 1ms/step - loss: 41.8644 - accuracy: 0.8849

[41.86442947387695, 0.8848999738693237]

## References

* [1] https://www.tensorflow.org/api_docs/python/tf/keras/Sequential
* [2] https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense
* [3] https://www.tensorflow.org/api_docs/python/tf/keras/layers/Flatten
* [4] https://machinelearningmastery.com/rectified-linear-activation-function-for-deep-learning-neural-networks/
* [5] https://developers.google.com/machine-learning/crash-course/multi-class-neural-networks/softmax
* [6] https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam
* [7] https://stats.stackexchange.com/questions/326065/cross-entropy-vs-sparse-cross-entropy-when-to-use-one-over-the-other